# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FaceRecognitionAttendanceSystem.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1144, 845)
        self.centralwidget = QtWidgets.QWidget(Form)
        self.centralwidget.setObjectName("centralwidget")
        self.face = QtWidgets.QLabel(self.centralwidget)
        self.face.setGeometry(QtCore.QRect(400, 30, 511, 321))
        self.face.setStyleSheet("\n"
"background-color: rgb(6, 6, 6);")
        self.face.setText("")
        self.face.setObjectName("face")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(950, 20, 160, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ImageAcquisition = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ImageAcquisition.setObjectName("ImageAcquisition")
        self.verticalLayout.addWidget(self.ImageAcquisition)
        self.FaceDateSet = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.FaceDateSet.setObjectName("FaceDateSet")
        self.verticalLayout.addWidget(self.FaceDateSet)
        self.ModelTraining = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ModelTraining.setObjectName("ModelTraining")
        self.verticalLayout.addWidget(self.ModelTraining)
        self.FaceRecognition = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.FaceRecognition.setObjectName("FaceRecognition")
        self.verticalLayout.addWidget(self.FaceRecognition)
        self.client = QtWidgets.QListWidget(self.centralwidget)
        self.client.setGeometry(QtCore.QRect(400, 380, 341, 411))
        self.client.setObjectName("client")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.client.addItem(item)
        self.information = QtWidgets.QTextEdit(self.centralwidget)
        self.information.setGeometry(QtCore.QRect(30, 50, 311, 741))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.information.setFont(font)
        self.information.setObjectName("information")
        self.server = QtWidgets.QListWidget(self.centralwidget)
        self.server.setGeometry(QtCore.QRect(810, 380, 311, 411))
        self.server.setObjectName("server")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.server.addItem(item)
        Form.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Form)
        self.statusbar.setObjectName("statusbar")
        Form.setStatusBar(self.statusbar)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "MainWindow"))
        self.ImageAcquisition.setText(_translate("Form", "成员录入"))
        self.FaceDateSet.setText(_translate("Form", "数据处理"))
        self.ModelTraining.setText(_translate("Form", "模型训练"))
        self.FaceRecognition.setText(_translate("Form", "人脸识别"))
        __sortingEnabled = self.client.isSortingEnabled()
        self.client.setSortingEnabled(False)
        item = self.client.item(0)
        item.setText(_translate("Form", "客户端："))
        self.client.setSortingEnabled(__sortingEnabled)
        self.information.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">项目名称：人脸识别门禁系统</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">采用技术：python+OpenCV+pyQT5</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">项目组长：翁飞龙</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">项目组员： 1</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">       2</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">       3</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">       4</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>"))
        __sortingEnabled = self.server.isSortingEnabled()
        self.server.setSortingEnabled(False)
        item = self.server.item(0)
        item.setText(_translate("Form", "服务端："))
        self.server.setSortingEnabled(__sortingEnabled)
